package api.techchallenge.domain.core.exception;

public class RecursoNaoEncontratoException extends RuntimeException {
    public RecursoNaoEncontratoException(String message) {
        super(message);
    }
}
